### PR TITLE
update seata version to 0.5.2

### PR DESCRIPTION
**Pull request by hero-zhanghao**
update seata version to 0.5.2

### CODE REVIEW

**Comment by fangjian0423** [comment]
@slievrly please check it!

**Comment by hero-zhanghao** [comment]
Can updates be included in version 0.9.1?

**Comment by hero-zhanghao** [comment]
@fangjian0423 @slievrly Can somebody answer that?When will 0.9.1 be released? I am waiting.

**Comment by fangjian0423** [comment]
> @fangjian0423 @slievrly Can somebody answer that?When will 0.9.1 be released? I am waiting.

spring cloud alibaba plan to release new version next week and @slievrly will upgrade seata to the newest version.

**Comment by slievrly** [comment]
@fangjian0423

**Comment by hero-zhanghao** [comment]
@fangjian0423 Is the release schedule delayed?

**Comment by fangjian0423** [comment]
> @fangjian0423 Is the release schedule delayed?

yes, we have discussed the graduation of spring-cloud-alibaba.

After that, we will release new version.

**Pull request merged**
